#!/usr/bin/env php
<?php

require(__DIR__ . '/vendor/autoload.php');

use Mindgruve\Gruver\Application;
use Symfony\Component\Console\Input\ArgvInput;

/**
 * Replace with Symfony Finder Component
 */

$application = new Application('gruver','0.7.1');
$application->add(new \Mindgruve\Gruver\Command\InstallCommand());
$application->add(new \Mindgruve\Gruver\Command\BuildCommand());
$application->add(new \Mindgruve\Gruver\Command\RunCommand());
$application->add(new \Mindgruve\Gruver\Command\DeployCommand());
$application->add(new \Mindgruve\Gruver\Command\PromoteCommand());
$application->add(new \Mindgruve\Gruver\Command\RollbackCommand());
$application->add(new \Mindgruve\Gruver\Command\CheckCommand());
$application->add(new \Mindgruve\Gruver\Command\StatusCommand());
$application->add(new \Mindgruve\Gruver\Command\CleanupCommand());
$application->add(new \Mindgruve\Gruver\Command\LoadConfigCommand());

/**
 * Doctrine Commands
 **/
$application->add(new \Mindgruve\Gruver\Command\Doctrine\OrmCreateCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\OrmUpdateCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\OrmGenerateProxiesCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationDiffCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationExecuteCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationGenerateCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationMigrateCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationStatusCommand());
$application->add(new \Mindgruve\Gruver\Command\Doctrine\MigrationVersionCommand());

$input = new ArgvInput();
$application->run($input);