project:
    name: ~
    email_notifications: []
    public_services: ~
directories:
    config_dir:     '/etc/gruver'
    data_dir:       '/var/lib/gruver'
    templates_dir:  '/var/lib/gruver/templates'
    releases_dir:   '/var/lib/gruver/releases'
    migrations_dir: '/var/lib/gruver/migrations'
    cache_dir:      '/var/lib/gruver/cache'
    proxy_dir:      '/var/lib/gruver/proxy'
    logging_dir:    '/var/log/gruver'
binaries:
    docker_binary: 'docker'
    docker_compose_binary: 'docker-compose'
    sqlite3_binary: 'sqlite3'
database:
    driver: 'pdo_sqlite'
    user: ~
    password: ~
logging:
    adapters:
      deployment:
          type: 'stream'
          level: 'info'
      error:
          type: 'stream'
          level: 'error'
config:
    dev_mode:                 false
    automatic_deployment:     false
    docker_compose_files:     []
    date_format:              'Ymd'
    health_checks:            []
    remove_exited_containers: true
    remove_orphan_images:     true
    email_notifications:      [ 'ksimpson@mindgruve.com' ]
events:
    pre_build: ~
    post_build: ~
    pre_run: ~
    post_run: ~
    pre_promote: ~
    post_promote: ~
    pre_rollback: ~
    post_rollback: ~
    pre_cleanup: ~
    post_cleanup: ~
    pre_status: ~
    post_status: ~