application:
    name: 'mindgruve.com'
    email_notifications: ['ksimpson@mindgruve.com']
staging:
    allowed_ips: []
    url_pattern:  '%s-$d.staging1.mindgruve.com'
production:
    hosts: [ 'www.mindgruve.com', 'mindgruve.com' ]
config:
    automatic_deployment: false
    docker_binary: '/usr/bin/docker'
    docker_compose_binary: '/usr/local/bin/docker-compose'
    health_checks: []
    remove_exited_containers: true
    remove_orphan_images: true
events:
    pre_build:
      - echo 'processing pre_build'
    post_build:
      - echo 'processing post_build'
    pre_promote: ~
    post_promote: ~
    pre_rollback: ~
    post_rollback: ~
    pre_cleanup:
      - echo 'processing pre_cleanup'
    post_cleanup:
      - echo 'processing post_cleanup'
    pre_status: ~
    post_status: ~