project:
    name: ~
    email_notifications: []
    public_services: ~
binaries:
    docker_binary: 'docker'
    docker_compose_binary: 'docker-compose'
    sqlite3_binary: 'sqlite3'
database:
    driver: 'pdo_sqlite'
    user: ~
    password: ~
    path: '/var/lib/gruver/data.db'
logging:
  default_directory: '/var/log/gruver'
  adapters:
    deployment:
        type: 'stream'
        path: '/var/log/gruver/deployment.log'
        level: 'info'
    error:
        type: 'stream'
        path: '/var/log/gruver/error.log'
        level: 'error'
config:
    automatic_deployment: false
    docker_compose_files: []
    date_format: 'Ymd'
    health_checks: []
    remove_exited_containers: true
    remove_orphan_images: true
    email_notifications: [ 'ksimpson@mindgruve.com' ]
events:
    pre_build: ~
    post_build: ~
    pre_run: ~
    post_run: ~
    pre_promote: ~
    post_promote: ~
    pre_rollback: ~
    post_rollback: ~
    pre_cleanup: ~
    post_cleanup: ~
    pre_status: ~
    post_status: ~