application:
    name: ~
    email_notifications: []
staging:
    allowed_ips: []
    url_pattern:  '%s-$d.staging1.mindgruve.com'
production:
    hosts: []
config:
    automatic_deployment: false
    docker_binary: 'docker'
    docker_compose_binary: 'docker-compose'
    sqlite3_binary: 'sqlite3'
    docker_compose_files: []
    date_format: 'Ymd'
    health_checks: []
    logging:
        default_directory: '/var/log/gruver'
        adapters:
            deployment:
                type: 'stream'
                path: '/var/log/gruver/deployment.log'
                level: 'info'
            error:
                type: 'stream'
                path: '/var/log/gruver/deployment.log'
                level: 'error'
    remove_exited_containers: true
    remove_orphan_images: true
events:
    pre_build:
      - echo 'processing pre_build'
    post_build:
      - echo 'processing post_build'
    pre_run:
      - echo 'processing pre_run'
    post_run:
      - echo 'processing post_run'
    pre_promote: ~
    post_promote: ~
    pre_rollback: ~
    post_rollback: ~
    pre_cleanup:
      - echo 'processing pre_cleanup'
    post_cleanup:
      - echo 'processing post_cleanup'
    pre_status: ~
    post_status: ~