#!/usr/bin/env php
<?php

require(__DIR__ . '/../vendor/autoload.php');

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

/**
 * Replace with Symfony Finder Component
 */

$application = new Application();
$application->add(new \Mindgruve\Gruver\Command\BuildContainerCommand());
$application->add(new \Mindgruve\Gruver\Command\DeployCommand());
$application->add(new \Mindgruve\Gruver\Command\PromoteContainerCommand());
$application->add(new \Mindgruve\Gruver\Command\RemoveSymlinksCommand());
$application->add(new \Mindgruve\Gruver\Command\RollbackCommand());
$application->add(new \Mindgruve\Gruver\Command\RunHealthChecksCommand());
$application->add(new \Mindgruve\Gruver\Command\RunTestsCommand());
$application->add(new \Mindgruve\Gruver\Command\StatusCommand());
$application->add(new \Mindgruve\Gruver\Command\SymlinkCommand());
$application->add(new \Mindgruve\Gruver\Command\VcsUpdateCommand());

$input = new ArgvInput();
$application->run($input);